BENEFICIARY_DISPLAY="Patient (Ins Policy Beneficiary)"
BENEFICIARY_TYPE="Patient"
CLASS=["group","Group","http://terminology.hl7.org/CodeSystem/coverage-class"]
CLASS_VALUE=["1234"]
IDENTIFIER_SYSTEM=["https://pediatrix.com/fhir/NamingSystem/coverage-id", "https://pediatrix.com/fhir/NamingSystem/insurance-policy-id"]
IDENTIFIER_VALUE=["TEST333345038900-{{FacilityId}}-5678", "TEST333345038900-{{FacilityId}}-1789"]
CODING=["MB", "Member Number", "http://terminology.hl7.org/CodeSystem/v2-0203"]
CODING_VALUE=["5678","1789"]
COVERAGE_NETWORK=["130", "131"]
COVERAGE_ORDER=[1, 2]
COVERAGE_PERIOD_START_DATE=["2023-01-01", "2023-02-02"]
COVERAGE_PERIOD_END_DATE=["2025-01-01", "2025-02-02"]
COVERAGE_STATUS=["active"]
COVERAGE_SUBSCRIBER_DISPLAY=["Subscriber (RelatedPerson)", "Subscriber (Patient)"]
COVERAGE_SUBSCRIBER_VALUE=["TEST333345038900-{{FacilityId}}-2000805", "TEST333345038900-{{FacilityId}}"]
COVERAGE_SUBSCRIBER_TYPE=["RelatedPerson", "Patient"]
RELATIONSHIP_CODE = ["spouse", "child", "other", "self"]
RELATIONSHIP_DISPLAY = ["Spouse", "Child", "Other", "Self"]
SUBSCRIBER_IDENTIFIER_SYSTEM= ["https://pediatrix.com/fhir/NamingSystem/relatedPerson-id", "https://pediatrix.com/fhir/NamingSystem/mrn-id"]

N_BENEFICIARY_DISPLAY="Related (Ins Policy Beneficiary)"
N_BENEFICIARY_TYPE="Person"
N_CLASS=["member","Member","http://terminology.hl7.org/CodeSystem/coverage-id"]
N_CLASS_VALUE=["9876"]
N_IDENTIFIER_SYSTEM=["https://pediatrix.com/fhir/NamingSystem/coverage-class", "https://pediatrix.com/fhir/NamingSystem/insurance-policy-ids"]
N_IDENTIFIER_VALUE="TEST333345038900-{{FacilityId}}-9876"
N_CODING=["group", "Group", "http://terminology.hl7.org/CodeSystem/v3-0203"]
N_CODING_VALUE=["9876"]
N_COVERAGE_NETWORK=["134"]
N_COVERAGE_ORDER=[5]
N_COVERAGE_PERIOD_START_DATE=["1999-01-01"]
N_COVERAGE_PERIOD_END_DATE=["2999-01-01"]
N_COVERAGE_STATUS=["NA"]
N_COVERAGE_SUBSCRIBER_DISPLAY="Subscriber (Guarantor)"
N_COVERAGE_SUBSCRIBER_VALUE="TEST333345038900-{{FacilityId}}-213456"
N_COVERAGE_SUBSCRIBER_TYPE="Guarantor"
N_RELATIONSHIP_CODE = ["S", "Other1", "Child1", "sp"]
N_RELATIONSHIP_DISPLAY = ["SP", "child01", "01", "00"]
N_SUBSCRIBER_IDENTIFIER_SYSTEM_RELATED_PERSON= "https://pediatrix.com/fhir/NamingSystem/relatedPerson"
N_SUBSCRIBER_IDENTIFIER_SYSTEM_PATIENT= "https://pediatrix.com/fhir/NamingSystem/mrn-ids"