ADMIT_TYPE="NB"
PATIENT_TYPE="CONF"
FINANCIAL_CLASS="COMM C"
ADMIT_DATETIME="2023-04-11"
DISCHARGE_DATETIME="2023-05-11"
PACID="pacid123"

CLASS_CODE="IMP"
CLASS_DISPLAY="inpatient encounter"
CLASS_SYSTEM="http://terminology.hl7.org/CodeSystem/v3-ActCode"
PRACTITIONER_CODE=["ATND","REF"]
PRACTITIONER_DISPLAY=["Attending","Referring"]
PRACTITIONER_SYSTEM="http://terminology.hl7.org/CodeSystem/v3-ParticipationType"
ENCOUNTER_STATUS="planned"