MRN="TEST333345038900"
LASTNAME="patient1"
FIRSTNAME="girl1testing"
MIDDLENAME="sprg"
DOB="2023-04-11"
DOD="2123-06-20"
GENDER=["male", "female", "unknown"]
ADDRESS1="111 first st"
ADDRESS2="apt 1"
CITY="somewhere"
STATE="fl"
ZIP="55555-5555"
COUNTRY="US"
ADDRESSUSE=["home","billing","work"]
ADDRESSTYPE="physical"
HOMEPHONE="(479)555-5874"
HOMEEMAIL="pid1@gmail.com"
WORKPHONE="(479)555-5875"
WORKEMAIL="pid12@gmail.com"
PHONETYPE=["home","mobile","work"]
HOSPITALPATIENTNUMBER="9543332222"
SSN="999999999"
#MULTIPLEBIRTH in HL7 message will transform to mulitplebirth integer if multiple birth is "Y"
BIRTHORDER=2
MR_CODE="MR"
MR_DISPLAY="Medical Record Number"
MR_SYSTEM="http://terminology.hl7.org/CodeSystem/v2-0203"
SSN_SYSTEM="http://hl7.org/fhir/sid/us-ssn"
SSN_CODE="SS"
SSN_DISPLAY="Social Security Number"
SSN_TERMINOLOGY_SYSTEM="http://terminology.hl7.org/CodeSystem/v2-0203"
PATIENT_INTERNAL_CODE="PI"
PATIENT_INTERNAL_DISPLAY="Patient Internal Identifier"
PATIENT_INTERNAL_SYSTEM="http://terminology.hl7.org/CodeSystem/v2-0203"
MARITALSTATUS_CODE=["M","U","D"]
MARITALSTATUS_DISPLAY=["Married", "Unmarried", "Divorced"]
MARITALSTATUS_SYSTEM="http://terminology.hl7.org/CodeSystem/v3-MaritalStatus"

# Below are place holders but we are not transforming admit date and dsicharge date from PID segment
#ADMITDATE=""
#DISCHARGEDATE=""