PRACTITIONER_CODING_CODE=["PRN","NPI"]
PRACTITIONER_CODING_DSIPLAY="National Provider Identifier"
PRACTITIONER_CODING_SYSTEM="http://terminology.hl7.org/CodeSystem/v2-0203"
PRACTITIONER_NPI_NUMBER=["15236798", "15236799"]
PRACTITIONER_GIVEN_NAME=["PHYSICIAN", "NURSE"]
PRACTITIONER_FAMILY_NAME=["SOM IP", "MOV GR"]

